apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
spec:
  env:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    processors:
      resource:
        attributes:
        - key: deployment.environment
          action: insert
          value: local
      batch:
    exporters:
      otlp/elastic:
        endpoint: ${HOST_IP}:8200
        tls:
          insecure: true
      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/elastic]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/elastic]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, otlp/elastic]
