kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "users-api.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "users-api.labels" . | nindent 4 }}
data:
  {{- if .Values.extraEnv -}}
  {{- range $key, $value := .Values.extraEnv }}
  {{ $value.name }}: {{ $value.value | quote}}
  {{- end -}}
  {{- end -}}