apiVersion: v2
name: users-api
description: A Helm chart for Kubernetes
home: https://github.com/joshwrightcodes/ed-demo-dapr
type: application
version: "0.1.0"
appVersion: "0.1.0.22e5461.1665027303"
kubeVersion: ">=1.24.0-0"
maintainers:
  - name: Josh Wright
    email: josh@wright.codes