apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "usergroups-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "usergroups-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "usergroups-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{ if or .Values.podAnnotations (include "usergroups-api.deployment.opentelemetry.annotations" .) (include "usergroups-api.deployment.dapr.annotations" .) -}}
      annotations:
        {{- include "usergroups-api.deployment.dapr.annotations" . | nindent 8 }}
        {{- include "usergroups-api.deployment.opentelemetry.annotations" . | nindent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "usergroups-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "usergroups-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://localhost:4317"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_LOGS_EXPORTER
              value: "otlp"
            - name: OTEL_SERVICE_NAME
              value: {{ include "usergroups-api.fullname" . }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.version={{ .Chart.AppVersion }},service.instance.id=$(POD_NAME),service.namespace=$(POD_NAMESPACE)"
            - name: APP_DaprOptions__SecretStore
              value: {{ include "usergroups-api.fullname" . }}-secrets
            - name: APP_DaprOptions__SecretDescriptors__0
              value: {{ include "usergroups-api.fullname" . }}-mailserver
            {{- with .Values.extraEnvs }}
            {{- . | toYaml | nindent 6 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "usergroups-api.fullname" . }}-env
          ports:
          {{- range $key, $value := .Values.containerPorts }}
            - name: {{ $key }}
              containerPort: {{ $value }}
              protocol: TCP
          {{- end }}
          {{- if .Values.startupProbe }}
          startupProbe: {{ toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
